apiVersion: v1
kind: Pod
metadata:
  name: nginx-high
  namespace: demo
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: priority
            operator: In
            values:
            - low
        topologyKey: kubernetes.io/hostname
  priorityClassName: high-priority
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    kubernetes.io/hostname: tx
