apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "v1"
    effect: "NoSchedule"
  - key: "key1"
    operator: "Equal"
    value: "v1"
    effect: "NoExecute"
