apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  namespace: demo
spec:
  containers:
  - name: tomcat
    image: tomcat
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-logs
      mountPath: /user/local/tomcat/logs
  - name: busybox
    image: busybox
    command: ["sh","-c","tall -f /logs/catalina*.log"]
    volumeMounts:
    - name: app-logs
      mountPath: /logs
  volumes:
  - name: app-logs
    emptyDir: {}
