apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoApp
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
      - name: kubernetes-demo-container
        image: hcwxd/kubernetes-demo
        ports:
        - containerPort: 3000
